# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [10]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [11]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [12]:
print(x.shape)

(40,)


5. Print the type of the previous array in question 3

In [13]:
print(type(x))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [117]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda\\Library\\include']

7. Print the dimension of the array in question 3


In [18]:
x.ndim

1

8. Create a boolean array with all the True values

In [20]:
bool_arr = np.array([1,2,3,4,5,6], dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True]


9. Create a two dimensional array




In [24]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [25]:
y = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
y    

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [27]:
x = np.arange(25)
x = x[::-1]
x

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [28]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [29]:
y = np.identity(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [32]:
arr = np.array([1, 2, 3, 4, 5]) 
arr = arr.astype('float64')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [35]:
arr1 = np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [36]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comparison = arr1 == arr2
equal_arrays = comparison.all()
print(equal_arrays)

False


17. Extract all odd numbers from arr with values(0-9)

In [47]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a[a%2 == 1]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [52]:
b = np.array([0,1,2,3,4,5,6,7,8,9])
-b[b%2 == 1]

array([-1, -3, -5, -7, -9])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [55]:
p=np.arange(0,14)
p[5:9] = 12
p

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13])

20. Create a 2d array with 1 on the border and 0 inside

In [60]:
y = np.ones((10,10))
y[1:-1,1:-1] = 0
y

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [62]:
 arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [63]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [65]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [66]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [68]:
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:3:2,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [2]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [75]:
z = np.random.randint((10,10))
a = [10,7,5]
b = [6,4,2]
print('random numbers are ',z)
print(z.max())
print(z.min())

random numbers are  [1 4]
4
1


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
R = np.intersect1d(a,b)
R

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [77]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [83]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names != "will"]

array([[-0.12375253, -1.22008991, -0.66699508,  0.11801031],
       [ 0.74542324,  0.72357135,  0.42597461, -0.58209628],
       [ 1.12550673, -0.57342117,  0.28871109, -0.34125891],
       [-2.42044852,  1.70081212,  0.40686865,  1.38406774],
       [-1.16293797, -0.46733738, -0.00626199,  0.21914665],
       [-1.4547073 , -0.47040242, -0.01436111, -0.16260455],
       [-0.8334973 ,  0.08495645, -0.19388855,  0.83497903]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [84]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
print(data[names != "will"])
print(data[names != "Joe"])

[[-1.07584816  1.10952042  0.51461552  0.48074147]
 [-0.50380731  2.78089915  0.61689006  0.14275605]
 [-1.92315167  0.64797335 -0.85633762 -1.2154999 ]
 [-0.05527218  1.97259097  0.20817694  1.82637044]
 [-0.10773104 -0.90598875  0.40006843  1.83103704]
 [-0.54932985  1.31235354 -0.7009059  -1.38123562]
 [ 0.34065033 -1.36540661 -0.04915676 -0.51459319]]
[[-1.07584816  1.10952042  0.51461552  0.48074147]
 [-1.92315167  0.64797335 -0.85633762 -1.2154999 ]
 [-0.05527218  1.97259097  0.20817694  1.82637044]
 [-0.10773104 -0.90598875  0.40006843  1.83103704]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [85]:
arr = np.random.randn(1,15).reshape(5,3)
arr

array([[-1.35135829, -2.75930034, -1.03602692],
       [-1.6764764 , -0.50062236,  0.41566538],
       [ 0.11093626,  0.66259359, -0.45568968],
       [-0.80650486, -0.10916545, -0.06086073],
       [-1.39203435, -1.76304945,  0.89845481]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [87]:
arr = np.random.randn(1,16).reshape(2,2,4)
arr

array([[[-2.03205565, -0.97711881, -0.02809955,  0.63038105],
        [ 0.26215522, -0.74460063,  0.99995066,  0.05945149]],

       [[-0.58743983,  0.38688093, -0.56407067,  0.30730649],
        [ 0.46135945, -0.40452304,  1.70656069, -0.55634057]]])

33. Swap axes of the array you created in Question 32

In [88]:
arr = np.random.randn(1,16).reshape(2,2,4)
data.T

array([[-1.07584816, -0.50380731, -1.92315167, -0.05527218, -0.10773104,
        -0.54932985,  0.34065033],
       [ 1.10952042,  2.78089915,  0.64797335,  1.97259097, -0.90598875,
         1.31235354, -1.36540661],
       [ 0.51461552,  0.61689006, -0.85633762,  0.20817694,  0.40006843,
        -0.7009059 , -0.04915676],
       [ 0.48074147,  0.14275605, -1.2154999 ,  1.82637044,  1.83103704,
        -1.38123562, -0.51459319]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [90]:
P = np.arange(10)
P = np.sqrt(R)
np.where(P<0.5,0,P)

array([1.41421356, 2.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [94]:
a = np.random.randn(12)
b = np.random.randn(12)
np. maximum(a,b)

array([-0.62186041,  0.02739728,  1.058136  ,  0.43689596, -0.75218613,
       -0.08698862,  1.33175725, -0.03571731,  0.74322299,  0.85077853,
        0.89886467, -0.17919644])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [96]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = set(names)
names

{'Bob', 'Joe', 'Will'}

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [97]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [116]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray = np.delete(sampleArray,1,axis = 1)
sampleArray


array([[34, 73],
       [82, 12],
       [53, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [110]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [111]:
n = np.random.randn(20)
n.cumsum()

array([-2.17000067, -1.10150332, -2.72861945, -2.76145627, -1.65407155,
       -0.69305483,  1.27190057,  1.70462306,  2.5269286 ,  1.75934057,
        3.41156482,  3.68290133,  4.96356296,  4.17569395,  4.37901485,
        5.98056803,  6.98133425,  6.35589569,  6.83283436,  5.82485668])